core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),  # Django admin route
    path("", include("apps.users.urls")),  # Auth routes - login / register
    path("", include("apps.ads.urls")),
    path("", include("apps.geolocation.urls")), 
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ads/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from ..users.models import Nurse
from ..address.models import Address

import geopy.distance

User = get_user_model()

BASE_PRICE = 500_000
TIME_DELTA_PRICE = 2_000_000
SERVICE_TYPE_BASE_PRICE = 500_000
HQ_COORD = (35.698747319698185, 51.35545136082422)
KILOMETER_BASE_PRICE = 100_000
MAX_DISTANCE_PRICE = 2_000_000
MIN_DISTANCE_PRICE = 0


class Ad(models.Model):
    class SERVICE_TYPES(models.TextChoices):
        ELDERLY = '1', _('Elderly care')
        DISABLILITY = '2', _('Caring for people with disabilities')
        OUTPATIENT = '3', _('Outpatient services'),
        INJECTION = '4', _('Injection services'),
        BLOOD = '5', _('Blood test'),
        PCR = '6', _('PCR test'),

    class GENDER(models.TextChoices):
        WOMAN = 'W', _('Woman')
        MAN = 'M', _('Man')

    class URGENCY(models.TextChoices):
        URGENT = '1', _('Urgent')
        NON_URGENT = '0', _('Non-urgent')

    creator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=2, choices=GENDER.choices)
    phone_number = models.CharField(max_length=11)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    service_type = models.CharField(
        max_length=2, choices=SERVICE_TYPES.choices)
    urgency = models.CharField(default=URGENCY.NON_URGENT, max_length=2, choices=URGENCY.choices)
    description = models.CharField(max_length=500, blank=True)
    accepted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"Ad info: {self.address}, {self.phone_number}, {self.service_type}, {self.start_time} until "
            f"{self.end_time}"
        )

    @property
    def price(self):
        delta = self.end_time - self.start_time
        service_type_coeff = service_type_coefficient[self.service_type]
        urgency_coeff = urgency_coeffecient[self.urgency]
        distance_price = 0
        if self.address:
            coord1 = (self.address.location[1],self.address.location[0])
            distance = geopy.distance.distance(coord1, HQ_COORD).km
            distance_price = distance * KILOMETER_BASE_PRICE
        distance_price = round(min(max(MIN_DISTANCE_PRICE, distance_price), MAX_DISTANCE_PRICE))
        return urgency_coeff * (
                BASE_PRICE + TIME_DELTA_PRICE * delta.days + SERVICE_TYPE_BASE_PRICE * service_type_coeff + distance_price)


service_type_coefficient = {
    Ad.SERVICE_TYPES.ELDERLY.value: 3,
    Ad.SERVICE_TYPES.DISABLILITY.value: 3,
    Ad.SERVICE_TYPES.OUTPATIENT.value: 0,
    Ad.SERVICE_TYPES.INJECTION.value: 1,
    Ad.SERVICE_TYPES.BLOOD.value: 2,
    Ad.SERVICE_TYPES.PCR.value: 1
}

urgency_coeffecient = {
    Ad.URGENCY.NON_URGENT.value: 1,
    Ad.URGENCY.URGENT.value: 2,
}


class NurseAd(models.Model):
    class STATUS(models.TextChoices):
        ACCEPTED = 'A', _('Accepted')
        STARTED = 'S', _('Started')
        FINISHED = 'F', _('Finished')

    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=2, choices=STATUS.choices, default=STATUS.ACCEPTED)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nurse_id}-{self.ad_id}-{self.status}"


class AdReview(models.Model):
    nurse_ad = models.OneToOneField(NurseAd, on_delete=models.CASCADE, related_name='review')
    score = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])
    review = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nurse_ad.nurse_id}-{self.nurse_ad.ad.creator_id}-{self.score}-{self.review}"

apps/geolocation/models.py
import json
from django.contrib.gis.db import models
from django.core.validators import RegexValidator
from django.contrib.gis.geos import Point

from ..ads.models import NurseAd


class TrackedPoint(models.Model):
    id = models.AutoField(primary_key=True)
    nurse_ad = models.ForeignKey(NurseAd, on_delete=models.CASCADE)
    location = models.PointField(default=Point(0, 0), blank=True)
    timestamp = models.DateTimeField()
    altitude = models.FloatField(blank=True, null=True)
    altitude_accuracy = models.FloatField(blank=True, null=True)
    accuracy = models.FloatField(blank=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.id, self.timestamp.isoformat())


class RouteLine(models.Model):
    id = models.AutoField(primary_key=True)
    nurse_ad = models.ForeignKey(NurseAd, on_delete=models.CASCADE)
    location = models.LineStringField(null=True, blank=True)
    color = models.CharField(
        max_length=7,
        default="#f5365c",
        validators=[RegexValidator("#[a-fA-F0-9]{6}")],
        help_text="Use hexadecimal format like #f5365c",
    )

    def __str__(self):
        return self.nurse_ad.nurse.username

    def get_geojson_feature(self):
        """
        Return self as GeoJSON feature instead of just plain geometry.

        Color property is used on a map to color geometry. Use only hexadecimal format.
        """

        return json.dumps(
            {
                "type": "Feature",
                "geometry": json.loads(self.location.geojson),
                "properties": {"color": self.color},
            }
        )

    @property
    def route_length(self):
        """
        Get length of the route.
        """
        geom = self.location.transform(3857, clone=True)
        return geom.length

apps/templates/includes/fixed-plugin.html
<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="fa fa-cog fa-2x"> </i>
        </a>
        <ul class="dropdown-menu">
            <li class="header-title"> Sidebar Background</li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <div class="badge-colors text-center">
                        <span class="badge filter badge-primary active" data-color="primary"></span>
                        <span class="badge filter badge-info" data-color="blue"></span>
                        <span class="badge filter badge-success" data-color="green"></span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="adjustments-line text-center color-change">
                <span class="color-label">LIGHT MODE</span>
                <span class="badge light-badge mr-2"></span>
                <span class="badge dark-badge ml-2"></span>
                <span class="color-label">DARK MODE</span>
            </li>
            <li class="button-container">

                <a href="https://appseed.us/jinja-template"
                   target="_blank" rel="noopener noreferrer"
                   class="btn btn-primary btn-block btn-round">More Templates</a>

                <a href="https://appseed.us/admin-dashboards"
                   target="_blank" rel="noopener noreferrer"
                   class="btn btn-default btn-block btn-round">
                    More Dashboards
                </a>
            </li>
            <li class="header-title">
                Coded by <a class="text-white"
                            target="_blank" rel="noopener noreferrer"
                            href="https://appseed.us">AppSeed</a>

            </li>
            <li>
                <br/>
            </li>
        </ul>

    </div>
</div>
  

apps/templates/includes/footer.html
<footer class="footer">
    <div class="container-fluid">
        <ul class="nav">
            <li class="nav-item">
                <a target="_blank" rel="noopener noreferrer"
                   href="#" class="nav-link">
                </a>
            </li>
        </ul>
        <div class="copyright">
            &copy; <a target="_blank" rel="sponsored noopener noreferrer"
                      href="#">Sharif University of Technology</a>
            - created by <a target="_blank" rel="noopener noreferrer" href="#">Saba Hashemi - Amirmahdi Namjoo - Sepehr Safari - Alireza Tajmirriahi</a>
        </div>
    </div>
</footer>
      

apps/templates/includes/navigation-rtl.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">RTL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav  mr-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="{% url 'logout' %}" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

apps/templates/includes/navigation.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
    <div class="container-fluid">
        <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
                <button type="button" class="navbar-toggler">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">
                TeleNurse
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">

            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}

                    <li class="search-bar input-group">
                        <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal">
                            <i class="tim-icons icon-zoom-split"></i>
                            <span class="d-lg-none d-md-block">Search</span>
                        </button>
                    </li>
                    <li class="dropdown nav-item">
                        <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            {% comment %} <div class="notification d-none d-lg-block d-xl-block"></div> {% endcomment %}
                            <div class=" d-none d-lg-block d-xl-block"></div>
                            <i class="tim-icons icon-sound-wave"></i>
                            <p class="d-lg-none">
                                Notifications
                            </p>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                            <li class="nav-link"><a href="#" class="nav-item dropdown-item">No new notifications</a>
                            </li>
                            {% comment %} <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li> {% endcomment %}
                        </ul>
                    </li>
                    <li class="dropdown nav-item">
                        <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                            <div class="photo">
                                <img src="{{ request.user.get_avatar_url }}" alt="Profile Photo">
                            </div>
                            <b class="caret d-none d-lg-block d-xl-block"></b>
                            <p class="d-lg-none">
                                Log out
                            </p>
                        </a>
                        <ul class="dropdown-menu dropdown-navbar">
                            <li class="nav-link"><a href="{% url 'user-profile' %}" class="nav-item dropdown-item">Profile</a>
                            </li>
                            <li class="dropdown-divider"></li>
                            <li class="nav-link"><a href="{% url 'logout' %}" class="nav-item dropdown-item">Log out</a>
                            </li>
                        </ul>
                    </li>
                    <li class="separator d-lg-none"></li>

                {% endif %}
            </ul>

        </div>
    </div>
</nav>
<div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="tim-icons icon-simple-remove"></i>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- End Navbar -->

apps/templates/includes/scripts.html
<!--   Core JS Files   -->
<script src="/static/assets/js/core/jquery.min.js"></script>
<script src="/static/assets/js/core/popper.min.js"></script>
<script src="/static/assets/js/core/bootstrap.min.js"></script>
<script src="/static/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!-- Chart JS -->
<script src="/static/assets/js/plugins/chartjs.min.js"></script>
<!--  Notifications Plugin    -->
<script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->
<script src="/static/assets/js/black-dashboard.min.js?v=1.0.0"></script><!-- Black Dashboard DEMO methods, don't include it in your project! -->
<script src="/static/assets/demo/demo.js"></script>
<script src="/static/assets/js/plugins/sweetalert2.all.min.js"></script>

  

apps/templates/includes/sidebar-rtl.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="#" class="simple-text logo-mini">
            PI
          </a>
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="#" class="simple-text logo-normal">
            Django Black
          </a>
        </div>

        <ul class="nav">
          <li class="{% if 'index' in segment %} active {% endif %}">
            <a href="/">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>لوحة القيادة</p>
            </a>
          </li>
          <li class="{% if 'icons' in segment %} active {% endif %}">
            <a href="/ui-icons.html">
              <i class="tim-icons icon-atom"></i>
              <p>الرموز</p>
            </a>
          </li>
          <li class="{% if 'maps' in segment %} active {% endif %}">
            <a href="/ui-maps.html">
              <i class="tim-icons icon-pin"></i>
              <p>خرائط</p>
            </a>
          </li>
          <li class="{% if 'notifications' in segment %} active {% endif %}">
            <a href="/ui-notifications.html">
              <i class="tim-icons icon-bell-55"></i>
              <p>إخطارات</p>
            </a>
          </li>
          <li class="{% if 'page-user' in segment %} active {% endif %}">
            <a href="/page-user.html">
              <i class="tim-icons icon-single-02"></i>
              <p>ملف تعريفي للمستخدم</p>
            </a>
          </li>
          <li class="{% if 'tables' in segment %} active {% endif %}">
            <a href="/ui-tables.html">
              <i class="tim-icons icon-puzzle-10"></i>
              <p>قائمة الجدول</p>
            </a>
          </li>
          <li class="{% if 'typography' in segment %} active {% endif %}">
            <a href="/ui-typography.html">
              <i class="tim-icons icon-align-center"></i>
              <p>طباعة</p>
            </a>
          </li>
          <li class="{% if 'rtl-support' in segment %} active {% endif %}">
            <a href="/page-rtl-support.html">
              <i class="tim-icons icon-world"></i>
              <p>دعم RTL</p>
            </a>
          </li>
          <li>
            <a href="{% url 'logout' %}" >
              <i class="tim-icons icon-button-power"></i>
              <p>Logout</p>
            </a>
          </li>
        </ul>
        
      </div>
    </div>

apps/templates/includes/submit-ad-content.html
<head>
    {{ form.media }}
    {% load humanize %}
</head>
<div class="row container-box justify-content-center">
    <div class="col-md-10 box align-self-center m-md-2 p-md-3">
        <div class="card">
            <div class="card-header">
                <h2 class="title">Submit Your Request</h2>
            </div>
            <form role="form" method="post" action="">
                {% csrf_token %}
                <div class="card-body">
                    {% if id %}
                        <div class="row">
                            <div class="col-md-12 pr-md-1">
                                <div class="form-group">
                                    <label for="id_id">ID</label>
                                    <input type="text" name="id" value="{{ id }}"
                                           class="form-control" disabled id="id_id">
                                </div>
                            </div>
                        </div>
                    {% endif %}

                {% if form.errors %}
                        <div id="form_errors" class="text-danger">
                            {% for key, value in form.errors.items %}
                                {{ value }}
                            {% endfor %}
                        </div>
                {% endif %}

                    <div class="row">
                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>First Name</label>
                                {{ form.first_name }}
                            </div>
                        </div>

                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Last Name</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Phone Number</label>
                                {{ form.phone_number }}
                            </div>
                            <span class="text-danger">{{ form.phone_number.errors }}</span>
                        </div>
                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Description</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Start Time</label>
                                {{ form.start_time }}
                            </div>
                            <span class="text-danger">{{ form.start_time.errors }}</span>
                        </div>

                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>End Time</label>
                                {{ form.end_time }}
                            </div>
                            <span class="text-danger">{{ form.end_time.errors }}</span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Service Type</label>
                                <div class="dropdown-items">
                                    {{ form.service_type }}
                                </div>
                            </div>
                        </div>

                        <div class="col-md-3 pr-md-1">
                            <div class="form-group">
                                <label>Patient Gender</label>
                                <div class="dropdown-items">
                                    {{ form.gender }}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 pr-md-1">
                            <div class="form-group">
                                <label>Urgency</label>
                                <div class="dropdown-items">
                                    {{ form.urgency }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">

                    </div>

                    <div class="row">

                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Address</label>
                                {{ form.address_details }}
                            </div>
                        </div>
                        {% if id %}
                            <div class="col-md-6 pr-md-1">
                                <div class="form-group">
                                    <label>
                                        Price
                                    </label>
                                    <input type="text" readonly value="{{ ad_price|intcomma }} IRR" class="form-control">

                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <div class="row">

                        <div class="col-md-6 pr-md-1">
                            <div class="form-group">
                                <label>Location</label>
                                <div class="m-md-2">
                                    {{ form.address_location }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <p>
                        <button type="submit" name="submit-ad" class="btn btn-fill btn-primary">Submit Ad</button>
                    </p>
                    {% if not user.is_authenticated %}
                        <p>Return to <a class="text-primary" href="{% url 'init' %}">Main Page</a></p>
                        <p>Have an account? <a class="text-primary" href="{% url 'login' %}">Login</a></p>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>

apps/templates/includes/submit-review.html
<div class="row container-box">
    <div class="col-md-8 box">
        <div class="card">
            <div class="card-header">
                <h2 class="title">Submit Your Review =)</h2>
            </div>

            <div class="solu_title">
                <h3>{{ nurse_ad.ad.first_name }} {{ nurse_ad.ad.last_name }}</h3>
            </div>
            <div class="solu_description">

                <div class="row">
                    <div class="col-md-6 pr-md-1">
                <ul>
                    <li><b>Address:</b> {{ nurse_ad.ad.address.details }}</li>
                    <li><b>Requested Service:</b> {{ nurse_ad.ad.get_service_type_display }}</li>
                </ul>
                    <li><b>Gender:</b> {{ nurse_ad.ad.get_gender_display }}</li>
                    <li><b>Phone Number:</b> {{ nurse_ad.ad.phone_number }}</li>

                    <li><b>Start Time:</b> {{ nurse_ad.ad.start_time }}</li>
                    <li><b>End Time:</b> {{ nurse_ad.ad.end_time }}</li>

                    <li><b>Status:</b> {{ nurse_ad.get_status_display }}</li>

                </ul>
            </div>
            <form role="form" method="post" action="">
                {% csrf_token %}
                <div class="card-body">

                    <div class="row">
                        <div class="col-md-12 pr-md-2">
                            <div class="form-group">
                                <label>Review</label>
                                {{ form.review }}
                            </div>
                        </div>


                    </div>

                    <div class="row">
                        <div class="col-md-12 pr-md-2">
                            <div class="form-group">
                                <label>Score</label>
                                {{ form.score }}
                            </div>
                        </div>
                    </div>


                </div>
                <div class="card-footer">
                    <p>
                        <button type="submit" name="submit-review" class="btn btn-fill btn-primary">Submit Review</button>
                    </p>
                    {% if not user.is_authenticated %}
                        <p>Return to <a class="text-primary" href="{% url 'init' %}">Main Page</a></p>
                        <p>Have an account? <a class="text-primary" href="{% url 'login' %}">Login</a></p>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>