core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),  # Django admin route
    path("", include("apps.users.urls")),  # Auth routes - login / register
    path("", include("apps.ads.urls")),
    path("", include("apps.geolocation.urls")), 
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/forms.py
from captcha.fields import ReCaptchaField
from django.contrib.gis import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm, UserChangeForm
from apps.address.models import Address
from apps.ads import models

from apps.users.models import Nurse

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        )
    )

    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = (
            "username",
            "password",
            "captcha"
        )


class BaseUserForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        )
    )

    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        )
    )

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        )
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "test@example.com", "class": "form-control"})
    )

    phone_number = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "+9123456789", "class": "form-control"}
        )
    )

    avatar = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput()
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "phone_number",
            "avatar"
        )


class RegisterForm(BaseUserForm, UserCreationForm):
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        )
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm Password", "class": "form-control"}
        )
    )

    captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = (*BaseUserForm.Meta.fields, "password1", "password2", "captcha")


class NurseRegisterForm(RegisterForm):
    document = forms.FileField(
        widget=forms.ClearableFileInput(),
        label="Document",
        required=True,
        help_text="Maximum file size: 200MB",
        max_length=200,
    )

    expertise_level = forms.ChoiceField(
        choices=models.Nurse.EXPERTISE_LEVELS.choices, required=True)

    class Meta:
        model = Nurse
        fields = (
            *RegisterForm.Meta.fields,
            "document",
            "expertise_level",
            )


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = (
            "old_password",
            "new_password1",
            "new_password2",
        )


class ActivationForm(forms.Form):
    uid = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "uid", "class": "form-control"}
        )
    )
    token = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "Token", "class": "form-control"}
        )
    )


class UpdateProfileForm(BaseUserForm, UserChangeForm):
    username = forms.CharField(
        disabled=True,
        required=False,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        )
    )

    address_details = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': "Address", 'class': "form-control"}
        )
    )

    address_location = forms.PointField(
        required=False,
        widget=forms.OSMWidget(attrs={'map_width': 400, 'map_height': 300})
    )

    def save(self, commit=True):
        address = Address.objects.create(details=self.cleaned_data['address_details'],
                                         location=self.cleaned_data['address_location'])
        user = super().save(commit=False)
        user.address = address
        user.save()
        return user


class NurseUpdateProfileForm(UpdateProfileForm, UserChangeForm):
    expertise_level = forms.ChoiceField(
        choices=models.Nurse.EXPERTISE_LEVELS.choices, required=True)

    class Meta:
        model = Nurse
        fields = (
            *UpdateProfileForm.Meta.fields,
            "expertise_level",
        )

apps/templates/accounts/activate_manual.html
{% extends "layouts/logged-out-base.html" %} {% block title %} Activate Account {% endblock %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

    <link rel="stylesheet" href="{% static 'assets/css/authentication/login.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/authentication/forms.css' %}">

    <section class="h-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">

                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0 login-title">Welcome To TeleNurse!</span>
                    </div>

                    <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

                        <form style="width: 23rem" role="form" method="post" action="">
                            {% csrf_token %}
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;"><b>Activate Account</b></h3>

                            {% if msg %}
                                <span class="text-danger">{{ msg | safe }}</span>
                            {% endif %}

                            <div class="form-group">
                                <label>uid</label>
                                {{ form.uid }}
                            </div>
                            <span class="text-danger">{{ form.uid.errors }}</span>


                            <div class="form-group">
                                <label>Token</label>
                                {{ form.token }}
                            </div>
                            <span class="text-danger">{{ form.token.errors }}</span>

                            <div class="pt-1 mb-4">
                                <button class="btn btn-fill btn-primary" type="submit">Login</button>
                            </div>

                        </form>

                    </div>

                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="{% static 'assets/img/authentication/login.jpg' %}" alt="Login image" class="w-100 vh-100"
                         style="object-fit: cover; object-position: left;">
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/init-page.html
{% extends "layouts/logged-out-base.html" %} {% load static %} {% block title %} Init Start {% endblock %}

{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'assets/css/authentication/init.css' %}">

    <div class="row container-box">
        <div class="col-md-6 box">
            <div class="card">
                <form role="form" method="post" action="">
                    {% csrf_token %}

                    <div class="card-header">
                        <h3 class="title">Welcome to TeleNurse =)</h3>
                    </div>

                    <div class="card-body">
                        <a class="btn btn-fill btn-primary" href="/login">Go To Login Page</a>
                        <a class="btn btn-fill btn-primary" href="/submit_ad">Submit Request</a>

                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/login.html
{% extends "layouts/logged-out-base.html" %} {% block title %} Login {% endblock %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

    <link rel="stylesheet" href="{% static 'assets/css/authentication/login.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/authentication/forms.css' %}">

    <section class="h-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">

                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0 login-title">Welcome To TeleNurse!</span>
                    </div>

                    <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

                        <form style="width: 23rem" role="form" method="post" action="">
                            {% csrf_token %}
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;"><b>Login</b></h3>

                            {% if msg %}
                                <span class="text-danger">{{ msg | safe }}</span>
                            {% endif %}

                            <div class="form-group">
                                <label>Username</label>
                                {{ form.username }}
                            </div>
                            <span class="text-danger">{{ form.username.errors }}</span>


                            <div class="form-group">
                                <label>Password</label>
                                {{ form.password }}
                            </div>
                            <span class="text-danger">{{ form.password.errors }}</span>


                            <div class="form-group">
                                <label>Captcha</label>
                                {{ form.captcha }}
                            </div>
                            <span class="text-danger">{{ form.captcha.errors }}</span>

                            <div class="pt-1 mb-4">
                                <button class="btn btn-fill btn-primary" type="submit">Login</button>
                            </div>

                            <p>Don't have an account? <a href="{% url 'register' %}" class="text-primary">Create</a></p>
                            <p>Return to <a class="text-primary" href="{% url 'init' %}">Main Page</a></p>
                            <p><a class="text-primary" href="{% url 'password_reset' %}">Forgot Password?</a></p>
                        </form>

                    </div>

                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="{% static 'assets/img/authentication/login.jpg' %}" alt="Login image" class="w-100 vh-100"
                         style="object-fit: cover; object-position: left;">
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/password_reset.html
{% extends "layouts/logged-out-base.html" %}

{% block title %} Login {% endblock %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                            <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                            autocomplete="email" maxlength="254" required id="id_email"
                                            placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark">Submit
                                            </button>
                                        </div>
                                </div>
                            </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <p style="color: rgba(255, 255, 255, 0.8);">
                                An email containing a link will be sent to this email. Use it to reset your password. Don't forget to check the Spam folder.
                            </p>
                            <br>
                            <div>
                                <p><a class="text-primary" href="{% url 'register' %}">Create A New Account</a></p>
                                <p><a class="text-primary" href="{% url 'login' %}">Back To Login</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
{% endblock content %}

apps/templates/accounts/password_reset_complete.html
{% extends "layouts/logged-out-base.html" %}

{% block title %} Password Reset Compelete {% endblock title %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info" style="margin-bottom: 0; background-color: #344675;">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}"><b>Login Here</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

apps/templates/accounts/password_reset_confirm.html
{% extends "layouts/logged-out-base.html" %}

{% block title %} Password Reset {% endblock title%}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                    class="form-control" required id="id_new_password1"
                                                    placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                    required id="id_new_password2" class="form-control"
                                                    placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/templates/accounts/password_reset_email.html
{% autoescape off %}
    Dear {{ user.username }},
    In order to initiate the password reset process for your {{ user.email }} TeleNurse Account,
    click the link below:

    {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

    If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

    Sincerely,
    TeleNurse
{% endautoescape %}

apps/templates/accounts/register.html
{% extends "layouts/logged-out-base.html" %} {% block title %} Login {% endblock %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% block content %}

    <link rel="stylesheet" href="{% static 'assets/css/authentication/login.css' %}">

    <section class="h-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">

                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0 register-title">Welcome To TeleNurse!</span>
                    </div>

                    <div class="d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">

                        <form role="form" method="post"
                              action="?type={% if is_nurse_form %}nurse{% else %}user{% endif %}"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;"><b>Sign Up</b></h3>

                            {% if msg %}
                                <span class="text-danger">{{ msg | safe }}</span>
                            {% endif %}

                            {% if success %}
                                <p class="col-md-8">
                                    Please <a href="{% url 'login' %}">authenticate</a> using the new account.
                                </p>
                            {% else %}
                                <div class="row mb-4">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>First Name</label>
                                            {{ form.first_name }}
                                        </div>
                                        <span class="text-danger">{{ form.first_name.errors }}</span>
                                    </div>

                                    <div class="col">
                                        <div class="form-group">
                                            <label>Last Name</label>
                                            {{ form.last_name }}
                                        </div>
                                        <span class="text-danger">{{ form.last_name.errors }}</span>
                                    </div>

                                </div>

                                <div class="row mb-4">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Username</label>
                                            {{ form.username }}
                                        </div>
                                        <span class="text-danger">{{ form.username.errors }}</span>
                                    </div>

                                    <div class="col">
                                        <div class="form-group">
                                            <label>Email</label>
                                            {{ form.email }}
                                        </div>
                                        <span class="text-danger">{{ form.email.errors }}</span>
                                    </div>

                                </div>

                                <div class="row mb-4">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Password</label>
                                            {{ form.password1 }}
                                        </div>
                                        <span class="text-danger">{{ form.password1.errors }}</span>
                                    </div>

                                    <div class="col">
                                        <div class="form-group">
                                            <label>Confirm Password</label>
                                            {{ form.password2 }}
                                        </div>
                                        <span class="text-danger">{{ form.password2.errors }}</span>
                                    </div>

                                </div>

                                <div class="row mb-4">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Phone Number</label>
                                            {{ form.phone_number }}
                                        </div>
                                        <span class="text-danger">{{ form.phone_number.errors }}</span>
                                    </div>

                                    {% if is_nurse_form %}
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Expertise Level</label>
                                            <br>
                                            {{ form.expertise_level }}
                                        </div>
                                        <span class="text-danger">{{ form.expertise_level.errors }}</span>
                                    </div>
                                    {% endif %}
                                </div>

                                <div class="row mb-4">
                                    <div class="col">
                                        <div class="form-group">
                                            <label>Avatar</label>
                                        </div>
                                        <div class="col-md-6 pr-md-1">
                                            {{ form.avatar }}
                                        </div>
                                        <span class="text-danger">{{ form.avatar.errors }}</span>
                                    </div>
                                </div>

                                <div class="row mb-4">
                                    {% if is_nurse_form %}
                                        <div class="col">
                                            <div class="form-group">
                                                <label>Documents</label>
                                            </div>
                                            <div class="col-md-6 pr-md-1">
                                                {{ form.document }}
                                            </div>
                                            <span class="text-danger">{{ form.document.errors }}</span>
                                        </div>
                                    {% endif %}

                                </div>

                                <div class="form-group">
                                    <label>Captcha</label>
                                    {{ form.captcha }}
                                </div>
                                <span class="text-danger">{{ form.captcha.errors }}</span>

                                <div class="pt-1 mb-4">
                                    <button class="btn btn-fill btn-primary" type="submit">Sign Up</button>
                                </div>

                                <p>
                                    {% if is_nurse_form %}
                                        <a href="{% url 'register' %}?type=user" class="text-primary">Register as
                                            User</a>
                                    {% else %}
                                        <a href="{% url 'register' %}?type=nurse" class="text-primary">Register as
                                            Nurse</a>
                                    {% endif %}
                                </p>

                                <p>Have an account? <a href="{% url 'login' %}" class="text-primary">Login</a></p>
                                <p>Return to <a class="text-primary" href="{% url 'init' %}">Main Page</a></p>
                            {% endif %}


                        </form>
                    </div>

                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="{% static 'assets/img/authentication/register.jpg' %}" alt="Signup image"
                         class="w-100 vh-100"
                         style="object-fit: cover; object-position: left;">
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}