core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),  # Django admin route
    path("", include("apps.users.urls")),  # Auth routes - login / register
    path("", include("apps.ads.urls")),
    path("", include("apps.geolocation.urls")), 
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/ads/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from ..users.models import Nurse
from ..address.models import Address

import geopy.distance

User = get_user_model()

BASE_PRICE = 500_000
TIME_DELTA_PRICE = 2_000_000
SERVICE_TYPE_BASE_PRICE = 500_000
HQ_COORD = (35.698747319698185, 51.35545136082422)
KILOMETER_BASE_PRICE = 100_000
MAX_DISTANCE_PRICE = 2_000_000
MIN_DISTANCE_PRICE = 0


class Ad(models.Model):
    class SERVICE_TYPES(models.TextChoices):
        ELDERLY = '1', _('Elderly care')
        DISABLILITY = '2', _('Caring for people with disabilities')
        OUTPATIENT = '3', _('Outpatient services'),
        INJECTION = '4', _('Injection services'),
        BLOOD = '5', _('Blood test'),
        PCR = '6', _('PCR test'),

    class GENDER(models.TextChoices):
        WOMAN = 'W', _('Woman')
        MAN = 'M', _('Man')

    class URGENCY(models.TextChoices):
        URGENT = '1', _('Urgent')
        NON_URGENT = '0', _('Non-urgent')

    creator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=2, choices=GENDER.choices)
    phone_number = models.CharField(max_length=11)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    service_type = models.CharField(
        max_length=2, choices=SERVICE_TYPES.choices)
    urgency = models.CharField(default=URGENCY.NON_URGENT, max_length=2, choices=URGENCY.choices)
    description = models.CharField(max_length=500, blank=True)
    accepted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"Ad info: {self.address}, {self.phone_number}, {self.service_type}, {self.start_time} until "
            f"{self.end_time}"
        )

    @property
    def price(self):
        delta = self.end_time - self.start_time
        service_type_coeff = service_type_coefficient[self.service_type]
        urgency_coeff = urgency_coeffecient[self.urgency]
        distance_price = 0
        if self.address:
            coord1 = (self.address.location[1],self.address.location[0])
            distance = geopy.distance.distance(coord1, HQ_COORD).km
            distance_price = distance * KILOMETER_BASE_PRICE
        distance_price = round(min(max(MIN_DISTANCE_PRICE, distance_price), MAX_DISTANCE_PRICE))
        return urgency_coeff * (
                BASE_PRICE + TIME_DELTA_PRICE * delta.days + SERVICE_TYPE_BASE_PRICE * service_type_coeff + distance_price)


service_type_coefficient = {
    Ad.SERVICE_TYPES.ELDERLY.value: 3,
    Ad.SERVICE_TYPES.DISABLILITY.value: 3,
    Ad.SERVICE_TYPES.OUTPATIENT.value: 0,
    Ad.SERVICE_TYPES.INJECTION.value: 1,
    Ad.SERVICE_TYPES.BLOOD.value: 2,
    Ad.SERVICE_TYPES.PCR.value: 1
}

urgency_coeffecient = {
    Ad.URGENCY.NON_URGENT.value: 1,
    Ad.URGENCY.URGENT.value: 2,
}


class NurseAd(models.Model):
    class STATUS(models.TextChoices):
        ACCEPTED = 'A', _('Accepted')
        STARTED = 'S', _('Started')
        FINISHED = 'F', _('Finished')

    nurse = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=2, choices=STATUS.choices, default=STATUS.ACCEPTED)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nurse_id}-{self.ad_id}-{self.status}"


class AdReview(models.Model):
    nurse_ad = models.OneToOneField(NurseAd, on_delete=models.CASCADE, related_name='review')
    score = models.IntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])
    review = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nurse_ad.nurse_id}-{self.nurse_ad.ad.creator_id}-{self.score}-{self.review}"

apps/templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

{% load static %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<h2><b>Welcome To TeleNurse :)</b> </h2>

<div>
    <div class="row d-flex px-3 justify-content-center">
        <button type="button" class="btn btn-lg btn-info row d-flex justify-content-center mx-2">
            <i class="tim-icons icon-single-02"></i> <span class="badge badge-default mx-3"> {{users_count}} </span> Users
          </button>
          <button type="button" class="btn btn-lg btn-info row d-flex justify-content-center mx-2">
            <i class="tim-icons icon-single-02"></i> <span class="badge badge-default mx-3"> {{nurses_count}} </span> Nurses
          </button>
          <button type="button" class="btn btn-lg btn-info row d-flex justify-content-center mx-2">
            <i class="tim-icons icon-single-02"></i> <span class="badge badge-default mx-3"> {{ads_count}} </span> Ads
          </button>
      </div>


    {% for chart in charts %}
        <legend class="text-primary pt-4">{{chart.title}}</legend>
        <div class="card-body">
            <div class="chart-area">
                <canvas id="{{chart.id}}"></canvas>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}


<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{% static 'assets/js/index-charts.js' %}"></script>

<script>
    var data = JSON.parse("{{data|escapejs}}");
    $(document).ready(function() {
        data['charts'].forEach(chart => {
            initChart(chart);
        });
  });
</script>
{% endblock javascripts %}

apps/templates/home/nurse-detail.html
{% extends "layouts/base.html" %}

{% load static %}

{% load humanize %}

{% block title %} Ads {% endblock %}




<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    {% if nurse_ads %}
        <h2>There are <b class="text-secondary">{{ nurse_ads|length }}</b> records available:</h2>

        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/ads/ads-list.css' %}">

        <div class="section_our_solution">
            <div class="solution_cards_box">
                <div class="grid-container">
                    {% for ad in nurse_ads %}
                        <div class="solution_card">
                            <div class="hover_color_bubble"></div>
                            <div class="so_top_icon">
                                <svg id="Layer_1" enable-background="new 0 0 512 512" height="50" viewBox="0 0 512 512"
                                     width="40" xmlns="http://www.w3.org/2000/svg">
                                    <g>
                                        <g>
                                            <g>
                                                <g>
                                                    <path d="m47.478 452.317 295.441 19.76c5.511.369 10.277-3.8 10.645-9.31l28.393-424.517c.369-5.511-3.8-10.276-9.31-10.645l-295.441-19.76c-5.511-.369-10.276 3.8-10.645 9.31l-28.394 424.517c-.368 5.511 3.8 10.277 9.311 10.645z"
                                                          fill="#fae19e"></path>
                                                </g>
                                                <g>
                                                    <g>
                                                        <g>
                                                            <g>
                                                                <g>
                                                                    <path d="m17.5 504.177h226.14l79.96-79.605v-355.86c0-5.523-4.477-10-10-10h-296.1c-5.523 0-10 4.477-10 10v425.466c0 5.522 4.477 9.999 10 9.999z"
                                                                          fill="#fff9e9"></path>
                                                                </g>
                                                                <path d="m313.601 58.712h-40c5.523 0 10 4.477 10 10v355.861l-.258 40.078 40.258-40.078v-355.861c0-5.523-4.477-10-10-10z"
                                                                      fill="#fff4d6"></path>
                                                            </g>
                                                        </g>
                                                    </g>
                                                    <path d="m243.64 504.177v-70.253c0-5.523 4.477-10 10-10h69.96z"
                                                          fill="#ffeec2"></path>
                                                </g>
                                            </g>
                                            <g>
                                                <path d="m468.636 248.58-33.372.165v-50.826c0-9.183 7.463-16.662 16.673-16.708h.007c9.217-.046 16.693 7.371 16.693 16.562v50.807z"
                                                      fill="#fed23a"></path>
                                                <path d="m451.96 504.177c-10.362-10.277-16.196-24.263-16.208-38.857l-.062-73.973c0-.644.524-1.169 1.171-1.173l30.038-.149c.647-.003 1.171.517 1.171 1.161l.062 74.079c.012 14.531-5.749 28.472-16.015 38.756z"
                                                      fill="#54b1ff"></path>
                                                <path d="m451.959 469.333h-.01c-14.434.072-26.14-11.542-26.14-25.935v-213.527c0-6.778 5.477-12.283 12.255-12.316l27.626-.137c6.826-.034 12.378 5.49 12.378 12.316v213.436c0 14.38-11.687 26.091-26.109 26.163z"
                                                      fill="#fdf385"></path>
                                                <path d="m465.69 217.417-23.769.118c6.037.79 10.708 5.94 10.708 12.198v213.437c0 9.823-5.455 18.397-13.507 22.87 3.79 2.115 8.164 3.317 12.826 3.293h.01c14.422-.072 26.109-11.783 26.109-26.163v-213.436c.001-6.826-5.551-12.351-12.377-12.317z"
                                                      fill="#faee6e"></path>
                                                <path d="m491.274 247.925-71.615.355c-7.305.036-13.226 5.968-13.226 13.248 0 7.281 5.921 13.153 13.226 13.117l58.389-.29v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c0-7.28-5.922-13.152-13.226-13.116z"
                                                      fill="#54b1ff"></path>
                                                <g>
                                                    <path d="m491.274 247.925-38.441.188-.167 26.311 25.381-.067v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c.001-7.282-5.921-13.154-13.225-13.118z"
                                                          fill="#3da7ff"></path>
                                                </g>
                                            </g>
                                        </g>
                                        <g fill="#060606">
                                            <path d="m373.147 20.122-295.44-19.761c-9.631-.638-17.984 6.665-18.629 16.293l-2.311 34.557h-39.267c-9.649 0-17.5 7.851-17.5 17.5v425.466c0 9.649 7.851 17.5 17.5 17.5h226.141c1.96 0 3.902-.801 5.292-2.185l34.138-33.987c.347.074.701.133 1.065.157l58.282 3.898c9.302.614 18.005-6.952 18.629-16.293l28.393-424.515c.639-9.528-6.766-17.993-16.293-18.63zm-122.006 465.902v-52.1c0-1.378 1.122-2.5 2.5-2.5h51.9zm94.939-23.757c-.244 1.51-1.131 2.286-2.66 2.327l-46.28-3.096 31.752-31.611c1.414-1.407 2.209-3.32 2.209-5.315v-355.86c0-9.649-7.851-17.5-17.5-17.5h-77.993c-9.697 0-9.697 15 0 15h77.993c1.379 0 2.5 1.122 2.5 2.5v347.712h-62.46c-9.649 0-17.5 7.851-17.5 17.5v62.753h-218.641c-1.378 0-2.5-1.122-2.5-2.5v-425.465c0-1.378 1.122-2.5 2.5-2.5h178.168c9.697 0 9.697-15 0-15h-123.868l2.244-33.556c.244-1.511 1.131-2.286 2.661-2.327l295.44 19.76c1.511.244 2.287 1.131 2.328 2.661z"></path>
                                            <path d="m267.827 237.047h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z"></path>
                                            <path d="m267.827 289.332h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z"></path>
                                            <path d="m55.774 192.262c0 4.142 3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5h-204.553c-4.142 0-7.5 3.358-7.5 7.5z"></path>
                                            <path d="m91.807 139.977c0 4.142 3.358 7.5 7.5 7.5h132.487c4.142 0 7.5-3.358 7.5-7.5s-3.358-7.5-7.5-7.5h-132.487c-4.142 0-7.5 3.358-7.5 7.5z"></path>
                                            <path d="m194.755 438.787c-13.489.036-26.978.065-40.467.086-4.534.007-9.067.013-13.6.016-8.215.006-13.75-1.643-15.59-10.679-1.556-7.64-12.364-6.613-14.464 0-5.19 16.337-13.774 9.936-18.582-1.053-4.797-10.963-6.027-23.233-8.122-34.9-1.54-8.573-14.506-6.17-14.732 1.994-.298 10.751-1.302 21.331-4.031 31.758-2.815 10.758-7.034 21.097-11.222 31.376-3.651 8.961 10.867 12.816 14.464 3.988 3.711-9.108 7.427-18.266 10.193-27.714 5.14 12.36 15.774 26.34 30.927 18.101 2.819-1.533 5.452-3.712 7.763-6.253 7.88 9.106 19.609 8.388 30.584 8.375 15.627-.02 31.254-.054 46.881-.095 9.649-.025 9.667-15.025-.002-15z"></path>
                                            <path d="m505.932 246.439c-3.897-3.878-9.255-5.867-14.695-6.014l-5.668.028v-10.719c0-6.529-3.878-13.427-9.433-16.862v-15.098c0-31.069-48.372-30.934-48.372.146v15.1c-5.659 3.498-9.455 9.741-9.455 16.852v10.982c-24.966 1.7-25.037 39.745.028 41.232.16 33.575.152 66.6-.028 100.737-.049 9.414 14.949 9.966 15 .079.18-34.166.188-67.22.029-100.823l37.211-.185s-.048 110.848-.048 160.784c0 24.338-37.219 24.5-37.219-.253l.013-13.677c.585-9.68-14.387-10.583-14.973-.904v12.834c0 11 3.402 20.316 9.988 26.869.586 15.693 7.198 30.878 18.369 41.956 3.205 3.18 7.642 2.208 10.744-.182 11.365-11.385 17.769-26.394 18.169-42.414 4.951-4.931 9.908-9.896 9.908-26.896l.006-68.351c12.97 3.689 26.494-6.348 26.494-19.946v-90.672c0-5.523-2.155-10.709-6.068-14.603zm-72.623-5.727v-10.841c0-2.219 1.523-4.08 3.573-4.633l30.025-.149c.84.208 1.615.605 2.243 1.231.915.911 1.419 2.123 1.419 3.414v10.794zm18.671-52c4.604 0 9.155 4.514 9.155 9.062v12.166l-18.372.091v-12.111c.001-5.053 4.133-9.183 9.217-9.208zm-.011 303.901c-3.487-4.942-6.009-10.531-7.417-16.406 2.322.503 4.674.765 7.027.765 2.627 0 5.253-.326 7.839-.957-1.374 5.964-3.892 11.587-7.449 16.598zm45.031-140.899c0 7.101-11.452 7.66-11.452.131 0 0 .013-70.974.021-77.48.005-4.196-3.483-7.509-7.558-7.509l-58.389.29c-7.242 0-7.073-11.331.074-11.366l71.615-.355c3.463.295 5.359 2.168 5.688 5.617v90.672z"></path>
                                        </g>
                                    </g>
                                </svg>
                            </div>
                            <div class="solu_title">
                                <h3>{% if is_admin %} {{ ad.first_name }} {{ ad.last_name }} {% endif %}</h3>
                            </div>
                            <div class="solu_description">
                                <ul>
                                    <li><b>Requested Service:</b> {{ ad.get_service_type_display }}</li>

                                    {% if is_admin %}
                                        <li><b>Address:</b> {{ ad.address.details }}</li>
                                    {% endif %}

                                    <!-- here we can set icon for gender of patient -->
                                    <li><b>Gender:</b> {{ ad.get_gender_display }}</li>

                                    {% if is_admin %}
                                        <li><b>Phone Number:</b> {{ ad.phone_number }}</li>
                                    {% endif %}

                                    <li><b>Start Time:</b> {{ ad.start_time }}</li>
                                    <li><b>End Time:</b> {{ ad.end_time }}</li>

                                    {% if ad.urgency == '1' and is_admin %}
                                        <li>Request is <b style="color: red;">URGENT</b></li>
                                    {% endif %}

                                    {% if is_admin %}
                                        <li><b>Description:</b> {{ ad.description }}</li>
                                    {% endif %}

                                    {% if is_admin %}
                                        <li><b>Price:</b> {{ ad.price|intcomma }} IRR</li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div id="reviewModal" class="modal hide" tabindex="-1" role="dialog"></div>
            </div>
        </div>


    {% else %}
        There are no records for this nurse.
    {% endif %}


{% endblock content %}

apps/templates/home/nurse-list.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} UI Tables {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<link rel="stylesheet" href="{% static 'assets/css/home/nurse-list.css' %}">

<div class="row">
    <div class="col-md-12">
        <div class="card card-tasks">
            <div class="card-header">
                <h1 class="card-title"> Nurses </h1>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table tablesorter " id="">
                        <thead class=" text-primary">
                            <tr>
                                <th></th>
                                <th>
                                    First Name
                                </th>
                                <th>
                                    Last Name
                                </th>
                                <th>
                                    Username
                                </th>
                                {% if is_admin %}
                                    <th>
                                        Email
                                    </th>
                                    <th>
                                        Phone Number
                                    </th>
                                {% endif %}
                                <th>
                                    Expertise level
                                </th>
                                <th>
                                    Average
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for nurse in nurses %}
                            {% if not nurse.is_superuser %}
                            <tr>
                                <td>
                                    <div class="photo card avatar">
                                        <img src="{{ nurse.get_avatar_url }}" alt="Profile Photo">
                                    </div>
                                </td>
                                <td>
                                    {{ nurse.first_name }}
                                </td>
                                <td>
                                    {{ nurse.last_name }}
                                </td>
                                <td>
                                    {{ nurse.username }}
                                </td>
                                {% if is_admin %}
                                    <td>
                                        {{ nurse.email }}
                                    </td>
                                    <td>
                                        {{ nurse.phone_number }}
                                    </td>
                                {% endif %}
                                <td>
                                    {{ nurse.expertise_level }}
                                </td>
                                <td>
                                    {% if nurse.average != 0 %}
                                    {{ nurse.average }} / 5.0
                                    {% else %}
                                    Without Average
                                    {% endif %}
                                </td>
                                <td>
                                    <button class="btn btn-fill btn-primary"
                                        onclick="window.location.href='/nurse-detail?username={{ nurse.username }}';">Records</button>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/nurse-location.html
{% extends "layouts/base.html" %}

{% load static %}

{% load humanize %}

{% block extra_head %}
    <style>
        #map {
            height: 400px;
            margin: 16px 125px 16px 16px;
        }
    </style>
{% endblock extra_head %}
{% load humanize %}
{% block title %} Locations {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block onloadcall %}init_theme('{{ request.user.username }}');line_startup();{% endblock onloadcall %}

{% block content %}

    <link rel="stylesheet" href="{% static 'assets/css/home/nurse-location.css' %}">

    <div class="row">
        <div class="col-md-12">
            <div class="card card-tasks">
                <div class="card-header">
                    <h1 class="card-title"> Locations </h1>
                </div>
                <div id="map"></div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table tablesorter " id="">
                            <thead class=" text-primary">
                            <tr>
                                <th></th>
                                <th>
                                    First Name
                                </th>
                                <th>
                                    Last Name
                                </th>
                                <th>
                                    Username
                                </th>
                                <th>
                                    Phone Number
                                </th>
                                <th>
                                    Ad ID
                                </th>
                                <th>
                                   
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for nurse_ad in active_ads %}
                                    <tr>
                                        <td>
                                            <div class="photo card avatar">
                                                <img src="{{ nurse_ad.nurse.get_avatar_url }}" alt="Profile Photo">
                                            </div>
                                        </td>
                                       
                                        <td>
                                            {{ nurse_ad.nurse.first_name }}
                                        </td>
                                        <td>
                                            {{ nurse_ad.nurse.last_name }}
                                        </td>
                                        <td>
                                            {{ nurse_ad.nurse.username }}
                                        </td>
                                        <td>
                                            {{ nurse_ad.nurse.phone_number }}
                                        </td>
                                        <td>
                                            {{ nurse_ad.ad.id }}
                                        </td>

                                        <td>
                                            <button type="button" class="btn btn-fill btn-secondry" 
                                                onclick="toggleDetails('{{nurse_ad.id}}')">
                                                Toggle Details
                                            </button>
                                            <button type="button" class="btn btn-fill btn-primary" 
                                                onclick="setNurseId('{{nurse_ad.nurse.id}}')">
                                                Show Last Location on Map
                                            </button>
                                        </td>
                                    </tr>
                                    <tr id="details-{{nurse_ad.id}}" hidden>
                                        <td colspan="7">
                                            <div class="solu_description">
                                                <ul>
                                                    
                                                    <li><b>Requested Service:</b> {{ nurse_ad.ad.get_service_type_display }}</li>
                                                    <li><b>Urgency:</b> {{ nurse_ad.ad.get_urgency_display }}</li>
                
                                                    <li><b>Gender:</b> {{ nurse_ad.ad.get_gender_display }}</li>
                                                    <li><b>Phone Number:</b> {{ nurse_ad.ad.phone_number }}</li>
                
                                                    <li><b>Start Time:</b> {{ nurse_ad.ad.start_time }}</li>
                                                    <li><b>End Time:</b> {{ nurse_ad.ad.end_time }}</li>

                                                    <li><b>Description:</b> {{ nurse_ad.ad.description }}</li>
                                                    
                                                    <li><b>Address:</b> {{ nurse_ad.ad.address.details }}</li>

                                                    <li><b>Price:</b> {{ nurse_ad.ad.price|intcomma }} IRR</li>

                                                    {% if nurse_ad.ad.address.location %}
                                                    <button type="button" class="btn btn-secondry" 
                                                        onclick="locate_position('{{nurse_ad.ad.address.location.y}}', '{{nurse_ad.ad.address.location.x}}', true)">
                                                        Show on map
                                                    </button>
                                                    {% endif %}
                
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
           {% load static %}
        <script src="{% static 'assets/js/nurse-location.js' %}"></script>
{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}